### ISSUE TITLE
Remove NPM Errors

### ISSUE THREAD

**Issue by MarcusSorealheis** [yasa-org/yasa#16]
Such as this one: 
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
```

**Comment by kezhenxu94** [comment]
I hope you're trying the latest codes, but when I run `npm run build` or `npm run serve`, they all didn't show the error messages you paste above

**Comment by MarcusSorealheis** [comment]
https://github.com/yasa-org/yasa/issues/17 is a child of this parent issue.

**Comment by kezhenxu94** [comment]
What are left in this issue after #17 is resolved?

**Comment by MarcusSorealheis** [comment]
> @MarcusSorealheis What are left in this issue after #17 is resolved?

It seems that eliminating ACE removes many errors

**Comment by kezhenxu94** [comment]
> > @MarcusSorealheis What are left in this issue after #17 is resolved?
> 
> 
> 
> It seems that eliminating ACE removes many errors

Yes, in my side, I didn’t see any error now, nor vulnerability

**Comment by kezhenxu94** [comment]
@MarcusSorealheis please help to confirm, if that's the case in your side, close this issue please

**Comment by kezhenxu94** [comment]
Pretty sure there is no npm error now
